### ISSUE TITLE
`ripple-binary-codec` not compliant w/ hooksv3's transactors

### ISSUE THREAD

**Issue by wojake** [XRPL-Labs/verify-xrpl-signature#14]
There are some txs that we're not able to verify since `ripple-binary-codec` doesn't have hooksV3's xrpl definitions.

Use [@transia/xrpl.js](https://github.com/Transia-RnD/xrpl.js/tree/main/packages/ripple-binary-codec/src)

URITokenMint:
```
{
  account: 'rDazrn7oJvgMv9KCikYXZA9AYCVorrLEkb',
  tx: '12002D210000535A2200000001240053F43D201B0053F45A61400000003B9ACA0068400000000000002D73007504776A61618114FBE31B66DC445F9CA33703C9B9B118FB73F913478314F25E77B50863B1738D90C4FC8D6A759C911A8CD4F3E0107321ED684DB7CBD9BFF9B6E2D2EFE596366CBCC484855E45923F7B1DDB0FB5193FEE1D744083D6D6CDC8217CC161D3014C9A98E66F45EFB0EA7D792F3651EE20157F21C7B4AEE9451BAF98C1946014225D2EFEF57CDAA6568B939AA85539663EDA9B1F8401811484C32BE95D648DC526DC4FCB97EA280837904521E1F1'
}
Error: Could not decode the transaction blob (HEX) (fromParser for (TransactionType, UInt16) -> undefined )
    at exports.u (/hpdevkit_vol/node1/contract_fs/mnt/rw/state/index.js:71235:15)
    at /hpdevkit_vol/node1/contract_fs/mnt/rw/state/index.js:24861:27
    at Array.forEach (<anonymous>)
    at Manager.signTx (/hpdevkit_vol/node1/contract_fs/mnt/rw/state/index.js:24855:22)
    at async contract (/hpdevkit_vol/node1/contract_fs/mnt/rw/state/index.js:78951:34)
    at async invokeCallback (/hpdevkit_vol/node1/contract_fs/mnt/rw/state/index.js:39271:9)
```

**Comment by wojake** [comment]
oh nvm, fixed: https://github.com/XRPL-Labs/verify-xrpl-signature/commit/316e8e09a0551e54a0d55a22e03333fb0b0f3da6
